### PR TITLE
Use pthread_exit to terminate raft service.

### PR DESCRIPTION
**Pull request by szmyd**
Allow the process to handle termination of raft service rather than force process wide `exit()`

Addresses #535

### CODE REVIEW

**Comment by szmyd** [comment]
I dunno if this should have a compile time condition around it similar to:
```c++
#ifdef USE_PTHREAD_EXIT
pthread_exit(nullptr);
#else 
exit(-1)
#endif
```
to avoid behavior change for those relying on this?

**Comment by greensky00** [comment]
Does it work correctly on Mac? I believe it doesn't work at least on Windows. We should write a helper function that works differently according to compiler flag, as you mentioned.

**Comment by szmyd** [comment]
> Does it work correctly on Mac? I believe it doesn't work at least on Windows. We should write a helper function that works differently according to compiler flag, as you mentioned.

It definitely doesn't work on Windows; but _should_ on Mac...Mac has `pthread_exit(3)`. I guess the question is, if it's compile time determined what should be the default? `exit()`?

**Review by greensky00 — APPROVED** [review]
Looks good, let's revisit later.

**Pull request merged**
